### PR TITLE
DEV-7070 Allowing to add image inside a figure

### PR DESCRIPTION
**Pull request by albertosml**

### CODE REVIEW

**Comment by wvbe** [comment]
Thanks for the PR @albertosml, I like how you renamed and created a second operation to 1) not break any other configuration while 2) DRY'ing the code!

**Review by wvbe — APPROVED** [review]

**Comment by EvadeHaas** [comment]
Hi alberto,

Do note that this isn't the only operation that has this problem. The problem is that the operation is contextual while, the ":_open-image-browser-for-insert" get's a contextNode from the selection. You can offcourse find all operations that contextually insert an image. But you can also solve this in a more generic way, by introducing a new transform, that first checks if it already has a contextNodeId and otherwise retrieves it by looking at the selectionManager. 

Besides that noticed that you now made a change in a package that is actually a separate repository "dita-example-sx-modules-xsd-common-element-mod". If you would need to make a change in that package, you should make a change in the "dita-example-sx-modules-xsd-common-element-mod" repository, and then update the package in dita-example. Do note that the fontoxml-app-dita-demo-editor repository also uses these shared packages and you can probably also apply the same fix there.

**Comment by albertosml** [comment]
@EvadeHaas In that case, I would suggest to modify "transform/setContextNodeIdToSelectedElement" operation to check if we have a selected node yet, otherwise, we take the selected node looking at the selectionManager. Then, we would only need to do the change in fontoxml-base-flow, and this PR could be cancelled.

**Comment by EvadeHaas** [comment]
@albertosml I get what you're saying, but I don't think you can just change the behavior of that existing API. Because it is a public API.

**Comment by albertosml** [comment]
@EvadeHaas In that case, I would have to create a new transform that does this behaviour, and then, replace it by the another operation.

**Comment by EvadeHaas** [comment]
@albertosml yes, that is what I would do.  You can create this transform on application level, because all API's you need are public.

**Review by JCEntrena — APPROVED** [review]

**Review by DrRataplan — APPROVED** [review]

**Pull request merged**
